FROM python:3.11-slim-bullseye

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    libpq-dev build-essential

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements_gpio.txt .
RUN pip install --no-cache-dir -r requirements_gpio.txt

COPY . .

ENTRYPOINT ["python", "manage.py"]
CMD ["gpio-worker"]