# Generated by Django 5.2.8 on 2025-11-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPO', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zawor',
            name='name',
        ),
        migrations.AddField(
            model_name='zawor',
            name='real_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zawor',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
