# Generated by Django 5.2.8 on 2025-12-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPO', '0002_remove_zawor_name_zawor_real_id_alter_zawor_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wodomierz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.IntegerField(default=0)),
            ],
        ),
    ]
